Shop/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),
]

Shop/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('shop/', include('shop.urls')),
    path('user/', include('user.urls')),
    path('basket/', include('basket.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

Shop/shop/urls.py
from django.urls import path
from .views import ProductsListView
from django.conf import settings
from django.conf.urls.static import static

app_name = "shop"

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/user/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import (EmailVerificationView, UserLoginView, UserProfileView,
                        UserRegistrationView)

app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='signup'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

Shop/shop/models.py
import stripe as stripe
from django.db import models
from user.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', null=True, blank=True)
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='rub')
        return stripe_product_price

# class Favorite(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return f"{User.username}: {Product.name}"

Shop/shop/forms.py
from django.forms import ModelForm
from .models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ['slug', 'created', 'updated']
        readonly_fields = ['available']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

Shop/shop/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from .models import Product, ProductCategory


class IndexView(TitleMixin, TemplateView):
    template_name = 'shop/index.html'
    title = 'Top Shop'


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'shop/list.html'
    paginate_by = 3
    title = 'Top Shop - Каталог'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context

Shop/shop/templates/shop/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Top Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:index' %}">Каталог<i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'user:profile' user.id %}">Профиль</a>
                            </li>
                            {#                            <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы</a></li>#}
                            {% if user.is_superuser or user.is_staff %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">
                                        Админ-панель
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'user:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signup' %}"><i class="fas fa-sign-in-alt">Зарегистрироваться</i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}"><i class="fas fa-sign-in-alt">Войти</i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
{#<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>#}
{#<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"#}
<script src="
https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js
"></script>
<script integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
{#<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>#}

</body>

</html>

Shop/shop/templates/shop/base1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="shortcut icon" href="../static/img/favicon.ico">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
{% include '../block/navbar.html' %}
<div class="content">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

Shop/shop/templates/shop/create_product.html
{% extends 'shop/base.html' %}

{% block title %}
Создать продукт
{% endblock %}
{% block content %}
    <form action="" method="post" class="register">
    <h1>Создание продукта</h1>
    {% csrf_token %}
    {{ form.as_p }}
        <div class="center">
            <button class="btn">Создать</button>
        </div>
    </form>
{% endblock %}

Shop/shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">{{ product.price }}₽</p>
        {% if user.is_authenticated %}
        <form action="{% url "basket:basket_add" product.id %}" method="post">
            {% csrf_token %}
            {{ basket_product_form }}
            <input type="submit" value="Add to basket">
        </form>
        {% endif %}
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

Shop/shop/templates/shop/favorite_list.html
{% extends 'shop/base.html' %}

{% block title %}My Favorites{% endblock %}

{% block content %}
    <h2>Мое избранное</h2>
    {% if favorites %}
        <ul>
            {% for favorite in favorites %}
                <li><a href="{{ favorite.product.get_absolute_url }}">{{ favorite.product.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Список избранного пуст</p>
    {% endif %}
{% endblock %}

Shop/shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <!--    <div class="alert alert-light text-center" role="alert">-->
        <!--        Информационное сообщение-->
        <!--    </div>-->
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <h1 class="text-light mt-5">Top Shop</h1>
                    <h2 class="text-light">
                        Лучшие инструменты на Top Shop.
                        Бесплатная доставка по всему миру!
                    </h2>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'shop:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Shop/shop/templates/shop/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static '/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Top Shop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}" class="list-group-item">
                            {{ category.name }}
                        </a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'img/wallpaper.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'img/wallpaper1.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'img/wallpaper2.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in object_list %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a class="btn btn-outline-success"
                                       href="{% url 'products:basket_add' product.id %}">
                                        Отправить в корзину
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                                   tabindex="-1" aria-disabled="true">
                                    Предыдущая
                                </a>
                            </li>
                            {% for page in paginator.page_range %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'products:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                                    Следующая
                                </a>
                            </li>
                        </ul>
                    </nav>

                {% endif %}

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Top Shop {% now "Y" %}</p>
        </div>
    </footer>
{% endblock %}

Shop/shop/templates/shop/update_product.html
{% extends 'shop/base.html' %}

{% block title %}
Изменить продукт
{% endblock %}
{% block content %}
    <form action="" method="post" class="register">
    <h1>Редактировать продукт</h1>
    {% csrf_token %}
    {{ form.as_p }}
        <div class="center">
            <button class="btn">Сохранить изменения</button>
        </div>
    </form>
{% endblock %}